---

coverage:
  status:
    project: off
    patch: off
  notify:
    gitter:
      default:
        url: "https://webhooks.gitter.im/e/bc349fd27713d9fa74e7"
        threshold: 1%
  ignore:
    - "tests/data"
    - "tests/mock/compat-*"
    - "tests/test-*"