language: c
sudo: required
compiler:
- clang
- gcc

matrix:
  include:
  - compiler: gcc
    after_success: bash <(curl -s https://codecov.io/bash)

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq freebsd-buildutils libelf-freebsd-dev liblua5.2-dev libsqlite3-dev
- ci/install_atf.sh
- ci/install_lutok.sh
- ci/install_kyua.sh

cache:
  ccache: true
  directories:
   - /home/travis/atf
   - /home/travis/lutok
   - /home/travis/kyua

install:
  fmake CFLAGS="-I/usr/include/freebsd/ -ftest-coverage -fprofile-arcs" LIBELF=-lelf-freebsd LIBATF_C=/usr/lib/libatf-c.a

script:
  fmake CFLAGS="-ftest-coverage -fprofile-arcs" LIBELF=-lelf-freebsd LIBATF_C=/usr/lib/libatf-c.a check

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/53c5f65b01f3b0095e35
    on_success: change
    on_failure: always
    on_start: never