sudo: required
services:
  - docker

env:
  - CC=gcc-7
  - CC=clang-5.0

before_install:
  - docker build -t fubarnetes/bhyve-multiboot-ci -f ci/Dockerfile .

script:
  - docker run -i fubarnetes/bhyve-multiboot-ci build cc=${CC}
  - docker run -i fubarnetes/bhyve-multiboot-ci build CC=${CC}

after_success:
  - docker run -i fubarnetes/bhyve-multiboot-ci bash -c "build && coverage ${CODECOV_TOKEN}"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/53c5f65b01f3b0095e35
    on_success: change
    on_failure: always
    on_start: never
